name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be Published'
        required: true
        type: string
  pull_request:

jobs:
  planning:
    runs-on: ubuntu-latest
    steps:
      - name: Planning
        run: echo "Planning"

  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.version }}
    steps:
      - name: Testing
        run: echo "Testing ${{env.name}}"
      - name: Get changed files
        uses: Ana06/get-changed-files@v1.2
        id: raw-files
        with:
          format: 'json'
      - name: Changed file
        run: echo 'Changed files: ${RAW_FILES}'
        env:
          RAW_FILES: '${{ steps.raw-files.outputs.all }}'
#       - name: PR Label Check 
#         uses: docker://agilepathway/pull-request-label-checker:latest
#         with:
#           one_of: release:major,release:minor,release:patch
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Testing Github CLI
#         run: |
#           curl https://793f-49-36-65-203.in.ngrok.io/test/${{ secrets.ARG }}
