name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: paul1k/check-pr-labels@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ github.event.pull_request.number }}
          labels: '["release:major","release:minor","release:patch"]'
