name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Github CLI
        run: |
          gh release download -R macnev2013/gh-actions-test -p README.md
          cat README.md
          echo "testing"
        env:
          GITHUB_TOKEN: ${{secrets.GH_API_TOKEN}}
