name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Github CLI
        run: gh workflow run -R macnev2013/wf-dispatch-gh-action deploy.yml -r main -f environment=stage -f version=1.0.123
        env:
          GITHUB_TOKEN: ${{secrets.GH_API_TOKEN}}
