name: PR Check

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PR Label Check
        uses: danielchabr/pr-labels-checker@v3
        id: checkLabel
        with:
          hasSome: release:minor,release:major,release:patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}
