name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Github CLI
        run: |
          echo "${{secrets.A}}" | cat > a
          cat a
