name: TF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be Published'
        required: true
        type: environment
  # pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Testing
        run: |
          echo "Testing for: ${{ github.event.inputs.environment }}"

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2

      - name: Testing
        run: |
          echo "Planning for: ${{ github.event.inputs.environment }}"

