name: TF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be Published'
        required: true
        type: environment
  # pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Testing
        run: |
          echo "Testing for: ${{ github.event.inputs.environment }}"
      - name: Output test
        id: installer
        run: |
          apt-get update
      - name: Manual Approval
        uses: macnev2013/manual-approval@v1.0.17
        env:
          OP: ${{ steps.installer.outputs.result }}
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: macnev2013
          approval-wait: 120
          issue-title: |
            Terraform - Manual Approval for Job: ${{ github.job }}
          issue-body: |
            <details><summary>Show Plan</summary>
            ${OP}
            </details>
      - name: Testing
        run: |
          echo "Planning for: ${{ github.event.inputs.environment }}"

