name: TF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be Published'
        required: true
        type: environment
  # pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Testing
        run: |
          echo "Testing for: ${{ github.event.inputs.environment }}"
  plan:
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Testing
        run: |
          echo "Planning for: ${{ github.event.inputs.environment }}"

